# Generated by Django 3.2 on 2021-09-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestaetigungsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=255)),
                ('email_text', models.TextField()),
                ('aktiviert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ('-created_at', 'aktiviert'),
            },
        ),
        migrations.CreateModel(
            name='Versammlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='bsp.: Versammlung 28.09.2021', max_length=255)),
                ('wann', models.DateField()),
                ('wo', models.CharField(help_text='Rathhaussaal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('anmeldung_bestaetigt', models.BooleanField(default=False, editable=False)),
                ('versammlung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='versammlung.versammlung')),
            ],
        ),
    ]
