# Generated by Django 3.1.1 on 2020-10-17 17:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kita_representative', '0001_initial'),
        ('kita', '0001_initial'),
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='kitas',
            field=models.ManyToManyField(blank=True, null=True, related_name='kitas', related_query_name='kita', to='kita.Kita'),
        ),
        migrations.AlterField(
            model_name='email',
            name='representatives',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', related_query_name='parent', to='kita_representative.KitaRepresentative'),
        ),
    ]
