# Generated by Django 3.1.1 on 2020-11-21 19:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0002_auto_20201017_1727'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='email',
        #     name='friends',
        #     field=models.ManyToManyField(blank=True, null=True, related_name='friends', related_query_name='friends', to='kita_friends.KitaFriends'),
        # ),
        migrations.AlterField(
            model_name='emailsignature',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
