# Generated by Django 3.1.1 on 2021-01-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0003_auto_20201121_1947'),
        ('emailer', '0003_auto_20201121_2014'),
    ]

    operations = [
    ]
