# Generated by Django 3.1.1 on 2021-04-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0004_merge_20210116_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.email')),
            ],
        ),
    ]
