# Generated by Django 3.1.1 on 2020-09-20 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kita.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('postal_code', models.PositiveIntegerField(validators=[kita.models.validate_postal_code_number])),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddIndex(
            model_name='kita',
            index=models.Index(fields=['name', 'email', 'created_at'], name='kita_kita_name_671f20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kita',
            unique_together={('name', 'street_name', 'number', 'postal_code', 'email', 'representative')},
        ),
        migrations.AlterIndexTogether(
            name='kita',
            index_together={('name', 'email', 'representative')},
        ),
    ]
