# Generated by Django 3.1.1 on 2020-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kita',
            options={'get_latest_by': 'created_at', 'ordering': ['name']},
        ),
    ]
