# Generated by Django 3.1.1 on 2021-01-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kita', '0002_auto_20201121_2009'),
        ('kita', '0002_auto_20201121_1947'),
    ]

    operations = [
    ]
