# Generated by Django 3.2 on 2021-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kita', '0003_merge_20210116_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kita',
            name='id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
