# Generated by Django 3.1.1 on 2020-09-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitaRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('kita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kita.kita')),
            ],
            options={
                'ordering': ['-kita', '-name', '-first_name'],
                'get_latest_by': 'created_at',
                'unique_together': {('name', 'first_name', 'email', 'kita')},
            },
        ),
    ]
