# Generated by Django 3.1.1 on 2020-11-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kita_representative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitarepresentative',
            options={'get_latest_by': 'created_at', 'ordering': ['-kita', '-name', '-first_name'], 'verbose_name': 'Kita-Representative', 'verbose_name_plural': 'Kita-Representatives'},
        ),
    ]
