# Generated by Django 3.2 on 2021-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kita_representative', '0003_kitarepresentative_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitarepresentative',
            name='id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
