# Generated by Django 3.2 on 2021-05-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210415_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulecommander',
            options={'get_latest_by': 'earliest_execution_date', 'ordering': ['earliest_execution_date']},
        ),
        migrations.AlterModelOptions(
            name='scheduleresult',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
